# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieAPIproject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MovieAPIproject

  target 'MovieAPIprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAPIprojectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
